[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Khazad-dum",
    "EIN:",
    # Lorem ipsum
    "Lorem ipsum dolor.*",
    "Morbi fermentum varius arcu.*",
    "Etiam dictum augue.*",
    "Nulla facilisi.*",
    "Pellentesque et sagittis.*",
]
